<?php

namespace Database\Seeders;

use App\Modules\CBNCSAT\Models\CsatThreatCatalogue;
use Illuminate\Database\Seeder;

class CsatThreatCatalogueSeeder extends Seeder
{
    public function run(): void
    {
        $threats = [
            ['name' => 'Ransomware Attack', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'high', 'impact' => 'high', 'desc' => 'Malicious software that encrypts institutional data and demands ransom payment for decryption keys. Nigerian banks are increasingly targeted due to perceived willingness to pay.', 'cbn' => 'CBN Cybersecurity Framework §3.5 requires incident response plans specifically addressing ransomware. NIBSS has issued advisories on ransomware targeting Nigerian payment infrastructure.'],
            ['name' => 'Business Email Compromise (BEC)', 'source' => 'external', 'cat' => 'human', 'likelihood' => 'high', 'impact' => 'high', 'desc' => 'Targeted phishing attacks impersonating executives or trusted parties to initiate fraudulent wire transfers or data exfiltration.', 'cbn' => 'Nigeria ranks among the top 5 countries globally for BEC attacks. CBN requires awareness training specifically addressing BEC scenarios.'],
            ['name' => 'Distributed Denial of Service (DDoS)', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'high', 'impact' => 'moderate', 'desc' => 'Volumetric or application-layer attacks designed to overwhelm banking infrastructure and disrupt online and mobile banking services.', 'cbn' => 'Nigerian banks have experienced multi-day DDoS campaigns. CBN requires DDoS mitigation capabilities for all internet-facing banking services.'],
            ['name' => 'Phishing / Spear Phishing', 'source' => 'external', 'cat' => 'human', 'likelihood' => 'high', 'impact' => 'moderate', 'desc' => 'Deceptive emails or messages designed to harvest credentials or install malware. Spear phishing targets specific individuals with personalised content.', 'cbn' => 'CBN mandates quarterly phishing awareness training and simulation exercises for all banking staff.'],
            ['name' => 'Insider Threat — Malicious', 'source' => 'internal', 'cat' => 'human', 'likelihood' => 'moderate', 'impact' => 'high', 'desc' => 'Current or former employees, contractors, or business partners who intentionally misuse access to harm the institution through data theft, fraud, or sabotage.', 'cbn' => 'CBN requires background verification for all employees with access to critical systems and monitoring of privileged access activities.'],
            ['name' => 'Insider Threat — Negligent', 'source' => 'internal', 'cat' => 'human', 'likelihood' => 'high', 'impact' => 'moderate', 'desc' => 'Unintentional security breaches caused by employee errors, poor practices, or lack of awareness, including accidental data exposure and misconfiguration.', 'cbn' => 'CBN Training & Culture requirements (Domain 1) mandate regular awareness programmes to reduce negligent insider incidents.'],
            ['name' => 'USSD Channel Interception', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'moderate', 'impact' => 'high', 'desc' => 'Man-in-the-middle attacks on USSD sessions exploiting the unencrypted nature of USSD protocols to intercept financial transactions.', 'cbn' => 'Unique to Nigerian banking. CBN requires additional security controls for USSD-based financial services including session encryption and transaction limits.'],
            ['name' => 'ATM Jackpotting', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'moderate', 'impact' => 'high', 'desc' => 'Physical or logical attacks on ATM infrastructure causing machines to dispense cash without authorisation, using malware or hardware manipulation.', 'cbn' => 'CBN ATM Guidelines require physical security controls, transaction monitoring, and regular security assessments for ATM networks.'],
            ['name' => 'PoS Skimming / Terminal Compromise', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'moderate', 'impact' => 'moderate', 'desc' => 'Compromise of Point of Sale terminals to capture card data, often through physical skimming devices or malware installed on terminal software.', 'cbn' => 'CBN requires PCI DSS compliance for all card-accepting institutions and EMV chip migration for PoS terminals.'],
            ['name' => 'Supply Chain Attack', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'moderate', 'impact' => 'high', 'desc' => 'Compromise of third-party software, hardware, or service providers to gain access to the institution through trusted supply chain relationships.', 'cbn' => 'CBN External Dependency Management (Domain 4) requires due diligence and ongoing monitoring of all critical third parties.'],
            ['name' => 'Mobile Banking Malware', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'high', 'impact' => 'moderate', 'desc' => 'Malicious applications targeting mobile banking apps to steal credentials, intercept OTPs, or initiate unauthorised transactions.', 'cbn' => 'CBN requires mobile banking security including app integrity checks, certificate pinning, and jailbreak/root detection.'],
            ['name' => 'SQL Injection / Web Application Attacks', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'moderate', 'impact' => 'high', 'desc' => 'Exploitation of web application vulnerabilities to extract data, modify records, or gain unauthorised access to backend systems.', 'cbn' => 'CBN requires secure coding practices and regular application security testing for all internet-facing banking applications.'],
            ['name' => 'Advanced Persistent Threat (APT)', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'low', 'impact' => 'high', 'desc' => 'Sophisticated, long-term targeted attacks by well-resourced adversaries (nation-state or organised crime) seeking persistent access to banking systems.', 'cbn' => 'CBN requires advanced threat detection capabilities and threat hunting for systematically important financial institutions.'],
            ['name' => 'Third-Party Data Breach', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'moderate', 'impact' => 'high', 'desc' => 'Breach of a third-party service provider resulting in exposure of institutional or customer data.', 'cbn' => 'NDPA 2023 requires breach notification within 72 hours. CBN Domain 4 requires monitoring of third-party security posture.'],
            ['name' => 'SIM Swap Fraud', 'source' => 'external', 'cat' => 'human', 'likelihood' => 'high', 'impact' => 'moderate', 'desc' => 'Social engineering of telcos to transfer victim phone numbers to attacker-controlled SIMs, enabling interception of OTPs for banking transactions.', 'cbn' => 'Highly prevalent in Nigeria. CBN and NCC have issued joint guidelines on SIM swap controls. Banks required to implement additional authentication beyond SMS OTP.'],
            ['name' => 'Cryptojacking', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'moderate', 'impact' => 'low', 'desc' => 'Unauthorised use of institutional computing resources to mine cryptocurrency, causing performance degradation and increased costs.', 'cbn' => null],
            ['name' => 'Social Engineering — Vishing/Smishing', 'source' => 'external', 'cat' => 'human', 'likelihood' => 'high', 'impact' => 'moderate', 'desc' => 'Voice or SMS-based social engineering targeting bank employees or customers to extract sensitive information or credentials.', 'cbn' => 'CBN Consumer Protection Framework requires customer awareness campaigns on social engineering threats.'],
            ['name' => 'Cloud Service Misconfiguration', 'source' => 'internal', 'cat' => 'technical', 'likelihood' => 'moderate', 'impact' => 'high', 'desc' => 'Insecure configuration of cloud services exposing data or services to unauthorised access due to misconfigured permissions, open storage, or default credentials.', 'cbn' => 'CBN data residency requirements mandate all customer data remain within approved jurisdictions.'],
            ['name' => 'Watering Hole Attack', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'low', 'impact' => 'high', 'desc' => 'Compromise of websites frequently visited by banking sector employees to deliver targeted malware.', 'cbn' => null],
            ['name' => 'Physical Security Breach', 'source' => 'external', 'cat' => 'human', 'likelihood' => 'moderate', 'impact' => 'moderate', 'desc' => 'Unauthorised physical access to data centres, server rooms, or branch offices enabling theft of equipment, data, or installation of rogue devices.', 'cbn' => 'CBN requires physical access controls including biometric access to data centres and CCTV monitoring.'],
            ['name' => 'NIP/NIBSS Payment Fraud', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'high', 'impact' => 'moderate', 'desc' => 'Exploitation of vulnerabilities in the Nigeria Instant Payment (NIP) system or NIBSS infrastructure to initiate fraudulent transactions.', 'cbn' => 'NIBSS requires participating institutions to implement fraud monitoring and transaction velocity checks on all NIP transactions.'],
            ['name' => 'Data Exfiltration', 'source' => 'internal', 'cat' => 'technical', 'likelihood' => 'moderate', 'impact' => 'high', 'desc' => 'Unauthorised extraction of sensitive data from institutional systems through various channels including email, USB, cloud uploads, or encrypted tunnels.', 'cbn' => 'NDPA 2023 requires data protection impact assessments and DLP controls. CBN requires monitoring of data movements.'],
            ['name' => 'DNS Hijacking / Pharming', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'moderate', 'impact' => 'high', 'desc' => 'Redirection of banking website traffic to fraudulent sites through DNS manipulation to capture customer credentials.', 'cbn' => null],
            ['name' => 'API Security Exploitation', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'moderate', 'impact' => 'high', 'desc' => 'Exploitation of poorly secured APIs used for open banking, mobile banking, or third-party integrations to access customer data or initiate transactions.', 'cbn' => 'CBN Open Banking regulations require secure API design, authentication, rate limiting, and regular security testing.'],
            ['name' => 'Power/Infrastructure Failure', 'source' => 'natural', 'cat' => 'environmental', 'likelihood' => 'high', 'impact' => 'moderate', 'desc' => 'Extended power outages or infrastructure failures affecting data centre operations, particularly relevant given Nigeria\'s unreliable power grid.', 'cbn' => 'CBN BCP requirements mandate redundant power systems and DR capabilities. Specific to Nigerian infrastructure challenges.'],
            ['name' => 'Credential Stuffing', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'high', 'impact' => 'moderate', 'desc' => 'Automated use of stolen username/password pairs from data breaches to gain access to banking systems where customers reuse passwords.', 'cbn' => 'CBN requires multi-factor authentication for all internet and mobile banking channels.'],
            ['name' => 'Zero-Day Exploit', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'low', 'impact' => 'high', 'desc' => 'Exploitation of previously unknown vulnerabilities in software or hardware before vendors release patches.', 'cbn' => 'CBN requires vulnerability management programmes with compensating controls for zero-day exposures.'],
            ['name' => 'Card-Not-Present Fraud', 'source' => 'external', 'cat' => 'technical', 'likelihood' => 'high', 'impact' => 'moderate', 'desc' => 'Fraudulent online transactions using stolen card details for e-commerce and card-not-present transactions.', 'cbn' => 'CBN requires 3D Secure authentication and real-time transaction monitoring for all card-not-present transactions.'],
            ['name' => 'Regulatory Non-Compliance', 'source' => 'internal', 'cat' => 'human', 'likelihood' => 'moderate', 'impact' => 'high', 'desc' => 'Failure to comply with CBN, NDPA, or other regulatory requirements leading to sanctions, fines, or licence revocation.', 'cbn' => 'CBN can impose fines, revoke licences, or mandate remediation for non-compliance with cybersecurity requirements.'],
            ['name' => 'Agent Banking Network Fraud', 'source' => 'external', 'cat' => 'human', 'likelihood' => 'moderate', 'impact' => 'moderate', 'desc' => 'Fraud perpetrated through or against agent banking networks, including agent collusion, fake agents, or compromise of agent devices.', 'cbn' => 'CBN Agent Banking Guidelines require KYA (Know Your Agent) processes and transaction monitoring for agent networks.'],
        ];

        foreach ($threats as $t) {
            CsatThreatCatalogue::create([
                'threat_name' => $t['name'],
                'threat_source' => $t['source'],
                'threat_category' => $t['cat'],
                'typical_likelihood' => $t['likelihood'],
                'typical_impact' => $t['impact'],
                'description' => $t['desc'],
                'cbn_relevance_note' => $t['cbn'],
            ]);
        }

        $this->command->info('Seeded '.count($threats).' Nigerian banking threat catalogue entries.');
    }
}
