<?php

namespace Database\Seeders;

use App\Modules\CBNCSAT\Models\CsatIrQuestion;
use Illuminate\Database\Seeder;

class CsatIrQuestionsSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            // Category 1: Technologies and Connection Types (14 questions)
            ['cat' => 1, 'num' => 1, 'text' => 'Total number of Internet Service Provider (ISP) connections (including redundant connections)', 'l1' => 'No direct ISP connections', 'l2' => '1–20 connections', 'l3' => '21–100 connections', 'l4' => '101–500 connections', 'l5' => 'More than 500 connections', 'cbn' => false],
            ['cat' => 1, 'num' => 2, 'text' => 'Total number of unsecured external connections or entry points to the institution', 'l1' => 'No unsecured connections', 'l2' => '1–5 unsecured connections', 'l3' => '6–25 unsecured connections', 'l4' => '26–100 unsecured connections', 'l5' => 'More than 100 unsecured connections', 'cbn' => false],
            ['cat' => 1, 'num' => 3, 'text' => 'Wireless network access points', 'l1' => 'No wireless access', 'l2' => 'Isolated guest wireless only', 'l3' => 'Guest and internal wireless with segmentation', 'l4' => 'Wireless access to sensitive internal networks', 'l5' => 'Open wireless access with limited controls', 'cbn' => false],
            ['cat' => 1, 'num' => 4, 'text' => 'Personal devices allowed to connect to the corporate network (BYOD)', 'l1' => 'No BYOD permitted', 'l2' => 'BYOD limited to email only with MDM', 'l3' => 'BYOD with MDM and limited internal access', 'l4' => 'BYOD with broad internal network access', 'l5' => 'Unmanaged personal devices with full access', 'cbn' => false],
            ['cat' => 1, 'num' => 5, 'text' => 'Third parties, including vendors and business partners, with access to internal systems', 'l1' => 'No third-party access', 'l2' => '1–5 third parties with monitored access', 'l3' => '6–25 third parties with defined access controls', 'l4' => '26–100 third parties with varying access levels', 'l5' => 'More than 100 third parties with broad access', 'cbn' => false],
            ['cat' => 1, 'num' => 6, 'text' => 'Technology systems or applications that are past end-of-life (EOL) or no longer supported', 'l1' => 'No EOL systems in production', 'l2' => '1–5 EOL systems in isolated environments', 'l3' => '6–15 EOL systems with compensating controls', 'l4' => '16–50 EOL systems including some critical', 'l5' => 'More than 50 EOL systems including critical infrastructure', 'cbn' => false],
            ['cat' => 1, 'num' => 7, 'text' => 'Use of cloud computing services (IaaS, PaaS, SaaS)', 'l1' => 'No cloud services in use', 'l2' => 'Non-critical SaaS only (email, collaboration)', 'l3' => 'SaaS and PaaS for business applications', 'l4' => 'Core banking or customer data in cloud', 'l5' => 'Critical infrastructure including core banking fully in cloud', 'cbn' => false],
            ['cat' => 1, 'num' => 8, 'text' => 'Internally hosted or managed network devices and servers', 'l1' => 'Fewer than 25 devices', 'l2' => '25–100 managed devices', 'l3' => '101–500 managed devices', 'l4' => '501–5000 managed devices', 'l5' => 'More than 5000 managed devices', 'cbn' => false],
            ['cat' => 1, 'num' => 9, 'text' => 'Connections to or integration with FinTech service providers', 'l1' => 'No FinTech connections', 'l2' => '1–3 FinTech integrations with API controls', 'l3' => '4–10 FinTech integrations', 'l4' => '11–25 FinTech integrations', 'l5' => 'More than 25 FinTech integrations with broad data sharing', 'cbn' => true],
            ['cat' => 1, 'num' => 10, 'text' => 'Connections to or integration with NIBSS (NIP, NIBSS Instant Payment, etc.)', 'l1' => 'No direct NIBSS connections', 'l2' => 'Single NIBSS channel (NIP only)', 'l3' => 'Multiple NIBSS channels (NIP, NEFT, etc.)', 'l4' => 'High-volume NIBSS transactions with multiple channels', 'l5' => 'Systemically important NIBSS participant with real-time settlement', 'cbn' => true],
            ['cat' => 1, 'num' => 11, 'text' => 'Open banking or API-based third-party data sharing', 'l1' => 'No open banking APIs', 'l2' => 'Read-only APIs for account information', 'l3' => 'Payment initiation APIs with partner banks', 'l4' => 'Broad open banking APIs with multiple third parties', 'l5' => 'Extensive open banking ecosystem with real-time data sharing', 'cbn' => true],
            ['cat' => 1, 'num' => 12, 'text' => 'Use of internally developed applications vs. vendor-supported applications', 'l1' => 'All applications are vendor-supported', 'l2' => 'Minimal in-house development (1–5 apps)', 'l3' => 'Moderate in-house development (6–20 apps)', 'l4' => 'Significant in-house development including customer-facing', 'l5' => 'Core banking and critical systems are internally developed', 'cbn' => false],
            ['cat' => 1, 'num' => 13, 'text' => 'Use of USSD channel for financial transactions', 'l1' => 'No USSD services offered', 'l2' => 'USSD for balance inquiry only', 'l3' => 'USSD for basic transactions (transfers, airtime)', 'l4' => 'USSD for high-value transactions and account management', 'l5' => 'USSD as primary transaction channel with high volume', 'cbn' => true],
            ['cat' => 1, 'num' => 14, 'text' => 'Complexity of network architecture and segmentation', 'l1' => 'Simple flat network with basic firewall', 'l2' => 'Basic segmentation between DMZ and internal', 'l3' => 'Multi-tier segmentation with zone-based controls', 'l4' => 'Complex multi-segment architecture with micro-segmentation', 'l5' => 'Highly complex hybrid architecture spanning multiple data centres', 'cbn' => false],

            // Category 2: Delivery Channels (4 questions)
            ['cat' => 2, 'num' => 1, 'text' => 'Online/internet banking presence (personal and commercial)', 'l1' => 'No online banking services', 'l2' => 'Informational website only', 'l3' => 'Online banking with basic transactions', 'l4' => 'Full-service internet banking with bill payment and transfers', 'l5' => 'Advanced internet banking with investment, trade finance, and API access', 'cbn' => false],
            ['cat' => 2, 'num' => 2, 'text' => 'Mobile banking application (iOS, Android)', 'l1' => 'No mobile banking application', 'l2' => 'Basic mobile app (balance inquiry, statements)', 'l3' => 'Mobile app with P2P transfers and bill payment', 'l4' => 'Feature-rich mobile app with biometric auth and investment features', 'l5' => 'Mobile-first bank with mobile as primary channel for all services', 'cbn' => false],
            ['cat' => 2, 'num' => 3, 'text' => 'Point of Sale (PoS) terminal operations', 'l1' => 'No PoS operations', 'l2' => 'PoS acquiring through third-party processor only', 'l3' => 'Bank-managed PoS network (fewer than 5,000 terminals)', 'l4' => 'Large bank-managed PoS network (5,000–50,000 terminals)', 'l5' => 'Extensive PoS network (more than 50,000) with agent banking', 'cbn' => true],
            ['cat' => 2, 'num' => 4, 'text' => 'ATM operations and management', 'l1' => 'No ATM operations', 'l2' => 'Fewer than 50 ATMs, outsourced management', 'l3' => '50–200 ATMs with mixed management', 'l4' => '200–1000 ATMs with in-house management', 'l5' => 'More than 1000 ATMs with off-site locations and cash recyclers', 'cbn' => true],

            // Category 3: Online/Mobile Products and Technology Services (14 questions)
            ['cat' => 3, 'num' => 1, 'text' => 'Issue and manage debit cards', 'l1' => 'No debit card issuance', 'l2' => 'Basic debit card programme (domestic only)', 'l3' => 'Debit cards with international scheme (Visa/MasterCard)', 'l4' => 'Large debit card portfolio with contactless and tokenisation', 'l5' => 'Issuer and acquirer with virtual cards and multi-currency', 'cbn' => false],
            ['cat' => 3, 'num' => 2, 'text' => 'Issue and manage credit cards', 'l1' => 'No credit card programme', 'l2' => 'Small credit card programme (fewer than 5,000 cards)', 'l3' => 'Medium programme (5,000–50,000 cards)', 'l4' => 'Large programme (50,000–500,000) with rewards', 'l5' => 'Very large programme (more than 500,000) with premium tiers', 'cbn' => false],
            ['cat' => 3, 'num' => 3, 'text' => 'Issue and manage prepaid cards', 'l1' => 'No prepaid card issuance', 'l2' => 'Limited prepaid programme (gift cards only)', 'l3' => 'Travel and payroll prepaid cards', 'l4' => 'Broad prepaid programme including government disbursement', 'l5' => 'Large-scale prepaid issuer with virtual and physical cards', 'cbn' => false],
            ['cat' => 3, 'num' => 4, 'text' => 'Person-to-person (P2P) electronic payments', 'l1' => 'No P2P payment services', 'l2' => 'P2P within own customer base only', 'l3' => 'P2P via NIP to other banks', 'l4' => 'Instant P2P with social/chat integration', 'l5' => 'P2P payment platform operator with cross-border capability', 'cbn' => false],
            ['cat' => 3, 'num' => 5, 'text' => 'Originate or manage ACH/NEFT transactions', 'l1' => 'No ACH/NEFT origination', 'l2' => 'Low-volume ACH/NEFT (fewer than 1,000/month)', 'l3' => 'Medium volume (1,000–10,000/month)', 'l4' => 'High volume (10,000–100,000/month)', 'l5' => 'Very high volume (more than 100,000/month) or ACH operator', 'cbn' => true],
            ['cat' => 3, 'num' => 6, 'text' => 'Originate or manage domestic and international wire transfers', 'l1' => 'No wire transfer services', 'l2' => 'Domestic wire only, low volume', 'l3' => 'Domestic and international wire (fewer than 500/month)', 'l4' => 'High-volume wire transfers including correspondent banking', 'l5' => 'Major wire transfer hub with SWIFT direct and high-value RTGS', 'cbn' => false],
            ['cat' => 3, 'num' => 7, 'text' => 'Provide treasury management services to commercial clients', 'l1' => 'No treasury management services', 'l2' => 'Basic cash management for corporate clients', 'l3' => 'Treasury management with automated sweeps and reporting', 'l4' => 'Advanced treasury with FX, derivatives, and API integration', 'l5' => 'Full-service treasury with host-to-host, SWIFT for corporates', 'cbn' => false],
            ['cat' => 3, 'num' => 8, 'text' => 'Act as a merchant acquirer for card transactions', 'l1' => 'No merchant acquiring', 'l2' => 'Limited acquiring through third-party processor', 'l3' => 'Direct acquiring (fewer than 1,000 merchants)', 'l4' => 'Large acquiring portfolio (1,000–10,000 merchants)', 'l5' => 'Major acquirer (more than 10,000 merchants) with e-commerce', 'cbn' => false],
            ['cat' => 3, 'num' => 9, 'text' => 'Provide correspondent banking services or act as correspondent', 'l1' => 'No correspondent banking relationships', 'l2' => 'Fewer than 5 correspondent relationships', 'l3' => '5–20 correspondent relationships', 'l4' => 'More than 20 relationships including high-risk jurisdictions', 'l5' => 'Major correspondent bank with nested relationships', 'cbn' => false],
            ['cat' => 3, 'num' => 10, 'text' => 'Provide trade finance services (letters of credit, guarantees)', 'l1' => 'No trade finance services', 'l2' => 'Basic LC and guarantee issuance', 'l3' => 'Trade finance with document handling and SWIFT', 'l4' => 'High-volume trade finance with supply chain financing', 'l5' => 'Major trade finance hub with blockchain-based trade platforms', 'cbn' => false],
            ['cat' => 3, 'num' => 11, 'text' => 'Offer digital lending or automated loan origination', 'l1' => 'No digital lending', 'l2' => 'Online loan application with manual processing', 'l3' => 'Automated loan scoring with digital disbursement', 'l4' => 'AI-driven instant lending with mobile disbursement', 'l5' => 'Digital-only lending platform with embedded finance partnerships', 'cbn' => true],
            ['cat' => 3, 'num' => 12, 'text' => 'Provide wealth management or investment products digitally', 'l1' => 'No digital investment products', 'l2' => 'Fixed deposit placement via internet banking', 'l3' => 'Digital investment platform with mutual funds', 'l4' => 'Robo-advisory and automated portfolio management', 'l5' => 'Full digital wealth platform with trading and crypto custody', 'cbn' => false],
            ['cat' => 3, 'num' => 13, 'text' => 'Provide agent banking or mobile money services', 'l1' => 'No agent banking services', 'l2' => 'Fewer than 500 agents', 'l3' => '500–5,000 agents', 'l4' => '5,000–50,000 agents with USSD integration', 'l5' => 'More than 50,000 agents as primary rural channel', 'cbn' => true],
            ['cat' => 3, 'num' => 14, 'text' => 'Process or store customer biometric data (BVN verification, facial recognition)', 'l1' => 'No biometric data processing', 'l2' => 'BVN verification via NIBSS only', 'l3' => 'BVN plus liveness detection for onboarding', 'l4' => 'Biometric authentication for transactions', 'l5' => 'Extensive biometric ecosystem including facial and fingerprint', 'cbn' => true],

            // Category 4: Organisational Characteristics (9 questions)
            ['cat' => 4, 'num' => 1, 'text' => 'Mergers and acquisitions activity, including geographic expansion', 'l1' => 'No M&A activity in past 3 years', 'l2' => 'Minor acquisition completed and fully integrated', 'l3' => 'Active M&A with integration in progress', 'l4' => 'Multiple acquisitions with complex integration', 'l5' => 'Ongoing major M&A with cross-border subsidiaries', 'cbn' => false],
            ['cat' => 4, 'num' => 2, 'text' => 'Total number of employees with access to IT systems', 'l1' => 'Fewer than 100 employees', 'l2' => '100–500 employees', 'l3' => '501–2,000 employees', 'l4' => '2,001–10,000 employees', 'l5' => 'More than 10,000 employees', 'cbn' => false],
            ['cat' => 4, 'num' => 3, 'text' => 'IT staff turnover rate and cybersecurity talent retention', 'l1' => 'Less than 5% annual IT turnover', 'l2' => '5–10% turnover with succession planning', 'l3' => '10–20% turnover', 'l4' => '20–35% turnover with key-person risk', 'l5' => 'Greater than 35% turnover with critical skills gaps', 'cbn' => false],
            ['cat' => 4, 'num' => 4, 'text' => 'Users with elevated or privileged access (admin, root, DBA)', 'l1' => 'Fewer than 10 privileged users', 'l2' => '10–25 privileged users with PAM controls', 'l3' => '26–100 privileged users', 'l4' => '101–500 privileged users', 'l5' => 'More than 500 privileged users with limited oversight', 'cbn' => false],
            ['cat' => 4, 'num' => 5, 'text' => 'Changes to IT environment in the past 12 months', 'l1' => 'No significant IT changes', 'l2' => 'Minor system upgrades and patches', 'l3' => 'New system deployment or major upgrade', 'l4' => 'Multiple major changes including core banking migration', 'l5' => 'Transformational IT overhaul across multiple systems', 'cbn' => false],
            ['cat' => 4, 'num' => 6, 'text' => 'Disaster recovery facility ownership and management', 'l1' => 'Bank-owned and managed primary and DR sites', 'l2' => 'Bank-owned DR site with vendor support', 'l3' => 'Vendor-hosted DR facility with bank oversight', 'l4' => 'Shared DR facility with multiple tenants', 'l5' => 'No dedicated DR facility or reliance on ad-hoc arrangements', 'cbn' => true],
            ['cat' => 4, 'num' => 7, 'text' => 'Location and management of off-site tape/data backup', 'l1' => 'Bank-owned secure off-site facility with tested recovery', 'l2' => 'Vendor-approved off-site facility with SLA', 'l3' => 'Third-party storage with limited bank oversight', 'l4' => 'Off-site backup exists but recovery untested', 'l5' => 'No off-site backup or inadequate backup arrangements', 'cbn' => true],
            ['cat' => 4, 'num' => 8, 'text' => 'Number of branch locations and geographic distribution', 'l1' => 'Single location or fewer than 10 branches', 'l2' => '10–50 branches in one region', 'l3' => '51–200 branches across multiple states', 'l4' => '201–500 branches nationwide', 'l5' => 'More than 500 branches with international presence', 'cbn' => false],
            ['cat' => 4, 'num' => 9, 'text' => 'Regulatory examination findings and remediation status', 'l1' => 'No outstanding regulatory findings', 'l2' => 'Minor findings, all remediated', 'l3' => 'Moderate findings with remediation in progress', 'l4' => 'Significant findings with overdue remediation', 'l5' => 'Critical CBN findings with enforcement action', 'cbn' => true],

            // Category 5: External Threats (6 questions)
            ['cat' => 5, 'num' => 1, 'text' => 'Number of denial-of-service (DoS/DDoS) attacks experienced in the past 12 months', 'l1' => 'No DoS/DDoS attacks experienced', 'l2' => '1–2 minor incidents, all mitigated', 'l3' => '3–5 incidents with some service impact', 'l4' => '6–12 incidents with customer-facing disruption', 'l5' => 'More than 12 incidents or sustained campaigns', 'cbn' => false],
            ['cat' => 5, 'num' => 2, 'text' => 'Cyber extortion, blackmail, or ransom demands received', 'l1' => 'No extortion or blackmail attempts', 'l2' => '1 attempt, no payment, contained', 'l3' => '2–3 attempts with investigation required', 'l4' => '4–6 attempts including credible threats', 'l5' => 'More than 6 attempts or successful ransomware execution', 'cbn' => false],
            ['cat' => 5, 'num' => 3, 'text' => 'Ransomware incidents (attempted or successful)', 'l1' => 'No ransomware incidents', 'l2' => '1 blocked attempt', 'l3' => '2–3 attempts, all contained at perimeter', 'l4' => 'Ransomware reached endpoints but contained', 'l5' => 'Successful ransomware encryption of production systems', 'cbn' => false],
            ['cat' => 5, 'num' => 4, 'text' => 'Unplanned downtime of critical IT systems due to cyber events', 'l1' => 'No unplanned cyber-related downtime', 'l2' => 'Less than 1 hour total unplanned downtime', 'l3' => '1–4 hours of unplanned downtime', 'l4' => '4–24 hours of unplanned downtime', 'l5' => 'More than 24 hours or multiple extended outages', 'cbn' => false],
            ['cat' => 5, 'num' => 5, 'text' => 'Business email compromise (BEC) attacks targeting the institution', 'l1' => 'No BEC attacks identified', 'l2' => '1–3 BEC attempts, all detected and blocked', 'l3' => '4–10 BEC attempts with some reaching executives', 'l4' => 'BEC attempts resulting in investigation but no financial loss', 'l5' => 'Successful BEC attack resulting in financial loss or data exposure', 'cbn' => false],
            ['cat' => 5, 'num' => 6, 'text' => 'Volume and sophistication of phishing attacks targeting employees', 'l1' => 'Minimal phishing (fewer than 10 attempts/month)', 'l2' => 'Low volume (10–50/month), basic phishing', 'l3' => 'Moderate volume (50–200/month) with spear phishing', 'l4' => 'High volume (200–1000/month) with targeted campaigns', 'l5' => 'Very high volume (more than 1000/month) with advanced social engineering', 'cbn' => false],
        ];

        $categoryNames = CsatIrQuestion::CATEGORY_NAMES;

        foreach ($questions as $q) {
            CsatIrQuestion::create([
                'category_code' => $q['cat'],
                'category_name' => $categoryNames[$q['cat']],
                'question_number' => $q['num'],
                'question_text' => $q['text'],
                'level_1_criteria' => $q['l1'],
                'level_2_criteria' => $q['l2'],
                'level_3_criteria' => $q['l3'],
                'level_4_criteria' => $q['l4'],
                'level_5_criteria' => $q['l5'],
                'cbn_specific' => $q['cbn'],
            ]);
        }

        $this->command->info('Seeded 47 CBN-CSAT inherent risk questions across 5 categories.');
    }
}
